# Generated by Django 4.2.7 on 2024-02-19 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_sdet'),
    ]

    operations = [
        migrations.AddField(
            model_name='sdet',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sdet',
            name='location',
            field=models.TextField(null=True),
        ),
    ]
